version: 2.1
jobs:
  check-syntax:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Check PHP Syntax
          command: |
            sudo apt update
            sudo apt install -y php-cli
            sudo apt install -f
            find . -name \*.php -type f -print0 | xargs -0 -I {} php -l {}
  deploy-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Test Site (SSH)
          command: |
            scp -r * ${test_username}@test.sebsscholarship.org:~/staging/
            ssh ${test_username}@test.sebsscholarship.org 'rm -rf ~/test.sebsscholarship.org/* && mv ~/staging/* ~/test.sebsscholarship.org/'
  deploy-prod:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Production Site (SSH)
          command: |
            scp -r * ${prod_username}@sebsscholarship.org:~/staging/
            ssh ${prod_username}@sebsscholarship.org 'rm -rf ~/sebsscholarship.org/* && mv ~/staging/* ~/sebsscholarship.org/'
workflows:
  deploy:
    jobs:
      - check-syntax
      - deploy-test:
          requires:
            - check-syntax
          filters:
            branches:
              only: development
      - deploy-prod:
          requires:
            - check-syntax
          filters:
            branches:
              only: master