version: 2.0
jobs:
  deploy-test-site:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys
      - checkout
      - run:
        name: Deploy to test site
        command: |
          ssh $username@$hostname 'rm -rf ~/$hostname/*'
          scp -r * $username@$hostname:~/$hostname/

workflows:
  version: 2
  test-site:
    jobs:
      - deploy-test-site:
        filters:
          branches:
            only: development