version: 2.1
jobs:
  deploy-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Test Site (SSH)
          command: |
            ssh ${test_username}@test.sebsscholarship.org 'rm -rf ~/test.sebsscholarship.org/*'
            scp -r * ${test_username}@test.sebsscholarship.org:~/test.sebsscholarship.org/
  deploy-prod:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Test Site (SSH)
          command: |
            ssh ${test_username}@test.sebsscholarship.org 'rm -rf ~/test.sebsscholarship.org/*'
            scp -r * ${test_username}@test.sebsscholarship.org:~/test.sebsscholarship.org/
      - run:
          name: Deploy to Production Site (SSH)
          command: |
            ssh ${prod_username}@sebsscholarship.org 'rm -rf ~/sebsscholarship.org/*'
            scp -r * ${prod_username}@sebsscholarship.org:~/sebsscholarship.org/


workflows:
  test-development:
    jobs:
      - deploy-test:
        filters:
          branches:
            only: development
  deploy-master:
    jobs:
      - deploy-prod:
        filters:
          branches:
            only: master