version: 2.1
jobs:
  deploy-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Test Site (SSH)
          command: |
            scp -r * ${test_username}@test.sebsscholarship.org:~/staging/
            ssh ${test_username}@test.sebsscholarship.org 'rsync -a ~/staging/* ~/test.sebsscholarship.org/ && rm -rf ~/staging/*'
  deploy-prod:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploy to Production Site (SSH)
          command: |
            scp -r * ${prod_username}@sebsscholarship.org:~/staging/
            ssh ${prod_username}@sebsscholarship.org 'rsync -a ~/staging/* ~/sebsscholarship.org/ && rm -rf ~/staging/*'
workflows:
  deploy:
    jobs:
      - deploy-test:
          filters:
            branches:
              only: development
      - deploy-prod:
          filters:
            branches:
              only: master