version: 2
jobs:
  deploy-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Deploy to test site (SSH)
          command: |
            ssh $username@test.sebsscholarship.org 'rm -rf ~/test.sebsscholarship.org/*'
            scp -r * $username@test.sebsscholarship.org:~/test.sebsscholarship.org/

workflows:
  version: 2
  test-development:
    jobs:
      deploy-test:
        filters:
          branches:
            only:
              - development