name: Lint and Build

on:
  push:
    branches-ignore:
      - 'main'
      - 'staging'
  pull_request:
    branches:
      - 'staging'

jobs:
  lint:
    name: Lint for errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          VALIDATE_XML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
          VALIDATE_PHP: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_CSS: true

      - name: Install dependencies
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          composer:2 install -n

      - name: Build site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4.1.0 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --drafts"