name: Lint and Build

on: push

jobs:
  lint:
    name: Lint for errors
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_PHP: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_CSS: true

  build:
    name: Build the site
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Staging site configuration
        if: github.ref != 'refs/heads/main'
        run: |
          echo 'User-agent: * Disallow: /' > ${{ github.workspace }}/robots.txt
          sed -i 's_https://sebsscholarship.org_https://test.sebsscholarship.org_g' ${{ github.workspace }}/_config.yml

      - name: Build staging site
        if: github.ref != 'refs/heads/main'
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --drafts"

      - name: Build production site
        if: github.ref == 'refs/heads/main'
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          name: Built Site
          path: ${{ github.workspace }}/_site/

  deploy_staging:
    name: Deploy to Staging Server
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Built Site
          path: Built Site

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_KEY }}

      - name: Trust SSH key
        run: ssh-keyscan sebsscholarship.org > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          scp -r Built\ Site/* ${{ secrets.TEST_SSH_USER }}@sebsscholarship.org:~/staging/
          ssh ${{ secrets.TEST_SSH_USER }}@sebsscholarship.org 'rm -rf ~/test.sebsscholarship.org/* && mv ~/staging/* ~/test.sebsscholarship.org/'

  deploy_production:
    name: Deploy to Production Server
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Built Site
          path: Built Site

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Trust SSH key
        run: ssh-keyscan sebsscholarship.org > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          scp -r Built\ Site/* ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org:~/staging/
          ssh ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org 'rm -rf ~/sebsscholarship.org/* && mv ~/staging/* ~/sebsscholarship.org/'