name: Deploy to Test Site

on:
  pull_request:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to test site
      env:
        AWS_DEFAULT_REGION: us-east-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ec2 run-instances --image-id ami-08001e5dd84839da5 --count 1 --instance-type t3a.nano --key-name ssh1 --security-group-ids sg-0ec8231c0259cdb15 --block-device-mappings "[{\"DeviceName\":\"/dev/sdf\",\"Ebs\":{\"VolumeSize\":5,\"DeleteOnTermination\":true}}]"
