name: Deploy to Production Site

on:
  push:
    branches: [ master ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check PHP
        run: |
          sudo apt update
          sudo apt install -y php-cli
          sudo apt install -f
          find . -name \*.php -type f -print0 | xargs -0 -I {} php -l {}

  build:
    needs: [check-syntax]
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Build the site
          run: |
            docker run \
            -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:3.8 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --drafts"

        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: Built Site
            path: ${{ github.workspace }}/_site/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - run: ssh-keyscan sebsscholarship.org > ~/.ssh/known_hosts

      - uses: actions/download-artifact@v1.0.0
        with:
          name: Built Site

      - name: Deploy
        run: |
          scp -r Built\ Site/* ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org:~/staging/
          ssh ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org 'rm -rf ~/sebsscholarship.org/* && mv ~/staging/* ~/sebsscholarship.org/'