name: Build and Deploy Production

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build the site
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
        id: extract_branch

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Install dependencies
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          composer:2 install -n

      - name: Build production site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4.1.0 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Built Site
          path: ${{ github.workspace }}/_site/

  deploy_production:
    name: Deploy to production server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Built Site
          path: Built Site

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Trust SSH key
        run: ssh-keyscan sebsscholarship.org > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          scp -r Built\ Site/* ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org:~/staging/
          ssh ${{ secrets.PROD_SSH_USER }}@sebsscholarship.org 'rm -rf ~/sebsscholarship.org/* \
          && mv ~/staging/* ~/sebsscholarship.org/'